//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro2DBarcode.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pro2DBarcode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 多区域二维码识别 的本地化字符串。
        /// </summary>
        internal static string chs_APPNAME {
            get {
                return ResourceManager.GetString("chs_APPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_ACCOUNTMANAGER {
            get {
                return ResourceManager.GetString("chs_BBI_ACCOUNTMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件信息 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_APPINFO {
            get {
                return ResourceManager.GetString("chs_BBI_APPINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_EXIT {
            get {
                return ResourceManager.GetString("chs_BBI_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_LOADROUTINE {
            get {
                return ResourceManager.GetString("chs_BBI_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_LOGIN {
            get {
                return ResourceManager.GetString("chs_BBI_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登出 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_LOGOUT {
            get {
                return ResourceManager.GetString("chs_BBI_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_NEWROUTINE {
            get {
                return ResourceManager.GetString("chs_BBI_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产统计 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_PRODUCTSTATISTIC {
            get {
                return ResourceManager.GetString("chs_BBI_PRODUCTSTATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_ROUTINEMANAGER {
            get {
                return ResourceManager.GetString("chs_BBI_ROUTINEMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_ROUTINESET {
            get {
                return ResourceManager.GetString("chs_BBI_ROUTINESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续运行 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_RUNCONTINUE {
            get {
                return ResourceManager.GetString("chs_BBI_RUNCONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单次运行 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_RUNONCE {
            get {
                return ResourceManager.GetString("chs_BBI_RUNONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止运行 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_RUNSTOP {
            get {
                return ResourceManager.GetString("chs_BBI_RUNSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_SYSTEMSET {
            get {
                return ResourceManager.GetString("chs_BBI_SYSTEMSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厂商信息 的本地化字符串。
        /// </summary>
        internal static string chs_BBI_VENDORINFO {
            get {
                return ResourceManager.GetString("chs_BBI_VENDORINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前程式 的本地化字符串。
        /// </summary>
        internal static string chs_BEI_CURRRENTROUTINE {
            get {
                return ResourceManager.GetString("chs_BEI_CURRRENTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        internal static string chs_BSBI_ACCOUNT {
            get {
                return ResourceManager.GetString("chs_BSBI_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 板卡状态: 的本地化字符串。
        /// </summary>
        internal static string chs_BSBI_BOARDSTATE {
            get {
                return ResourceManager.GetString("chs_BSBI_BOARDSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机状态: 的本地化字符串。
        /// </summary>
        internal static string chs_BSBI_CAMERASTATE {
            get {
                return ResourceManager.GetString("chs_BSBI_CAMERASTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string chs_BSBI_HELP {
            get {
                return ResourceManager.GetString("chs_BSBI_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程式 的本地化字符串。
        /// </summary>
        internal static string chs_BSBI_ROUTINE {
            get {
                return ResourceManager.GetString("chs_BSBI_ROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口状态 的本地化字符串。
        /// </summary>
        internal static string chs_BSBI_SERIALPORTSTATE {
            get {
                return ResourceManager.GetString("chs_BSBI_SERIALPORTSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string chs_BSBI_SET {
            get {
                return ResourceManager.GetString("chs_BSBI_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称: 的本地化字符串。
        /// </summary>
        internal static string chs_BSTI_CLIENTNAME {
            get {
                return ResourceManager.GetString("chs_BSTI_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前账户: 的本地化字符串。
        /// </summary>
        internal static string chs_BSTI_CURRENTACCOUNT {
            get {
                return ResourceManager.GetString("chs_BSTI_CURRENTACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前时间: 的本地化字符串。
        /// </summary>
        internal static string chs_BSTI_CURRENTTIME {
            get {
                return ResourceManager.GetString("chs_BSTI_CURRENTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试算法 的本地化字符串。
        /// </summary>
        internal static string chs_CHKE_ENABLEALGORITHM {
            get {
                return ResourceManager.GetString("chs_CHKE_ENABLEALGORITHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用上次程式 的本地化字符串。
        /// </summary>
        internal static string chs_CHKE_ENABLELASTROUTINE {
            get {
                return ResourceManager.GetString("chs_CHKE_ENABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存All 的本地化字符串。
        /// </summary>
        internal static string chs_CHKE_SAVEALL {
            get {
                return ResourceManager.GetString("chs_CHKE_SAVEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存NG 的本地化字符串。
        /// </summary>
        internal static string chs_CHKE_SAVENG {
            get {
                return ResourceManager.GetString("chs_CHKE_SAVENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存OK 的本地化字符串。
        /// </summary>
        internal static string chs_CHKE_SAVEOK {
            get {
                return ResourceManager.GetString("chs_CHKE_SAVEOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新程式对话框 的本地化字符串。
        /// </summary>
        internal static string chs_FRM_NEWROUTINE {
            get {
                return ResourceManager.GetString("chs_FRM_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程式管理对话框 的本地化字符串。
        /// </summary>
        internal static string chs_FRM_ROUTINEMANAGER {
            get {
                return ResourceManager.GetString("chs_FRM_ROUTINEMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程式参数设置对话框 的本地化字符串。
        /// </summary>
        internal static string chs_FRM_SETROUTINEPARAMETER {
            get {
                return ResourceManager.GetString("chs_FRM_SETROUTINEPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法参数 的本地化字符串。
        /// </summary>
        internal static string chs_GRPC_ALGORITHMPARAMETER {
            get {
                return ResourceManager.GetString("chs_GRPC_ALGORITHMPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预处理 的本地化字符串。
        /// </summary>
        internal static string chs_GRPC_PREPROCESS {
            get {
                return ResourceManager.GetString("chs_GRPC_PREPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理参数 的本地化字符串。
        /// </summary>
        internal static string chs_GRPC_PROCESSPARAMETER {
            get {
                return ResourceManager.GetString("chs_GRPC_PROCESSPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件语言: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_APPLANGUAGE {
            get {
                return ResourceManager.GetString("chs_LBLC_APPLANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机曝光 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_CAMERAEXPOSURE {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERAEXPOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机增益 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_CAMERAGAIN {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识码相机名称: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_CAMERANAMEFORBARCODE {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERANAMEFORBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_CLIENTNAME {
            get {
                return ResourceManager.GetString("chs_LBLC_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码类型 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_CODETYPE {
            get {
                return ResourceManager.GetString("chs_LBLC_CODETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_COORDINATE {
            get {
                return ResourceManager.GetString("chs_LBLC_COORDINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录名称: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_DIRECTORYNAME {
            get {
                return ResourceManager.GetString("chs_LBLC_DIRECTORYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录提示 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_DIRECTORYPROMPT {
            get {
                return ResourceManager.GetString("chs_LBLC_DIRECTORYPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗时: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_ELAPSETIME {
            get {
                return ResourceManager.GetString("chs_LBLC_ELAPSETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK颜色 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_FOUNDCOLOR {
            get {
                return ResourceManager.GetString("chs_LBLC_FOUNDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰度值: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_GRAYVALUE {
            get {
                return ResourceManager.GetString("chs_LBLC_GRAYVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像名称: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_IMAGENAME {
            get {
                return ResourceManager.GetString("chs_LBLC_IMAGENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判定面积 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_JUDGEAREA {
            get {
                return ResourceManager.GetString("chs_LBLC_JUDGEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NG颜色 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_NOTFOUNDCOLOR {
            get {
                return ResourceManager.GetString("chs_LBLC_NOTFOUNDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信包尾字符: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_PACKETEND {
            get {
                return ResourceManager.GetString("chs_LBLC_PACKETEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信包头字符: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_PACKETHEADER {
            get {
                return ResourceManager.GetString("chs_LBLC_PACKETHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入新程式的名称： 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_PROMOTION {
            get {
                return ResourceManager.GetString("chs_LBLC_PROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次品: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_PRONG {
            get {
                return ResourceManager.GetString("chs_LBLC_PRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 良品: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_PROOK {
            get {
                return ResourceManager.GetString("chs_LBLC_PROOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_PROTOTAL {
            get {
                return ResourceManager.GetString("chs_LBLC_PROTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 良率: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_PROYIELDRATIO {
            get {
                return ResourceManager.GetString("chs_LBLC_PROYIELDRATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果分隔符: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_RESULTSEPARATOR {
            get {
                return ResourceManager.GetString("chs_LBLC_RESULTSEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程式目录: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_ROUTINEDIRECTORY {
            get {
                return ResourceManager.GetString("chs_LBLC_ROUTINEDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按名称搜索 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_SEARCHBYNAMES {
            get {
                return ResourceManager.GetString("chs_LBLC_SEARCHBYNAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识码串口名称: 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_SERIALPORTNAMEFORBARCODE {
            get {
                return ResourceManager.GetString("chs_LBLC_SERIALPORTNAMEFORBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别超时 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_TIMEOUT {
            get {
                return ResourceManager.GetString("chs_LBLC_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别数量 的本地化字符串。
        /// </summary>
        internal static string chs_LBLC_TOBEFOUNDNUM {
            get {
                return ResourceManager.GetString("chs_LBLC_TOBEFOUNDNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string chs_RUN {
            get {
                return ResourceManager.GetString("chs_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用参数 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_APPLYPARAMETER {
            get {
                return ResourceManager.GetString("chs_SBTN_APPLYPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算判定 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_CALCULATEJUDGE {
            get {
                return ResourceManager.GetString("chs_SBTN_CALCULATEJUDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_CAMERASET {
            get {
                return ResourceManager.GetString("chs_SBTN_CAMERASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("chs_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_CLEARROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_CLEARROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("chs_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清零 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_COUNTCLEAR {
            get {
                return ResourceManager.GetString("chs_SBTN_COUNTCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_DELETEROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_DELETEROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_EDITROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_EDITROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_EXIT {
            get {
                return ResourceManager.GetString("chs_SBTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续测试 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_GRABCONTINUE {
            get {
                return ResourceManager.GetString("chs_SBTN_GRABCONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止采集 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_GRABSTOP {
            get {
                return ResourceManager.GetString("chs_SBTN_GRABSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测区域 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_INSPECTAREA {
            get {
                return ResourceManager.GetString("chs_SBTN_INSPECTAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一张 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_LAST {
            get {
                return ResourceManager.GetString("chs_SBTN_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载图像 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_LOADIMAGE {
            get {
                return ResourceManager.GetString("chs_SBTN_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_LOADROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_NEWROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一张 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_NEXT {
            get {
                return ResourceManager.GetString("chs_SBTN_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存参数 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_SAVEPARAMETER {
            get {
                return ResourceManager.GetString("chs_SBTN_SAVEPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_SEARCH {
            get {
                return ResourceManager.GetString("chs_SBTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线测试 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_TESTOFFLINE {
            get {
                return ResourceManager.GetString("chs_SBTN_TESTOFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单次测试 的本地化字符串。
        /// </summary>
        internal static string chs_SBTN_TESTONLINE {
            get {
                return ResourceManager.GetString("chs_SBTN_TESTONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string chs_SELECT {
            get {
                return ResourceManager.GetString("chs_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string chs_STOP {
            get {
                return ResourceManager.GetString("chs_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深圳市联合创新实业有限公司 的本地化字符串。
        /// </summary>
        internal static string chs_VENDORINFO {
            get {
                return ResourceManager.GetString("chs_VENDORINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ArmbandInspect 的本地化字符串。
        /// </summary>
        internal static string en_APPNAME {
            get {
                return ResourceManager.GetString("en_APPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager 的本地化字符串。
        /// </summary>
        internal static string en_BBI_ACCOUNTMANAGER {
            get {
                return ResourceManager.GetString("en_BBI_ACCOUNTMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppInfo 的本地化字符串。
        /// </summary>
        internal static string en_BBI_APPINFO {
            get {
                return ResourceManager.GetString("en_BBI_APPINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string en_BBI_EXIT {
            get {
                return ResourceManager.GetString("en_BBI_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        internal static string en_BBI_LOADROUTINE {
            get {
                return ResourceManager.GetString("en_BBI_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string en_BBI_LOGIN {
            get {
                return ResourceManager.GetString("en_BBI_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string en_BBI_LOGOUT {
            get {
                return ResourceManager.GetString("en_BBI_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string en_BBI_NEWROUTINE {
            get {
                return ResourceManager.GetString("en_BBI_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductStatistic 的本地化字符串。
        /// </summary>
        internal static string en_BBI_PRODUCTSTATISTIC {
            get {
                return ResourceManager.GetString("en_BBI_PRODUCTSTATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager 的本地化字符串。
        /// </summary>
        internal static string en_BBI_ROUTINEMANAGER {
            get {
                return ResourceManager.GetString("en_BBI_ROUTINEMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string en_BBI_ROUTINESET {
            get {
                return ResourceManager.GetString("en_BBI_ROUTINESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunContinue 的本地化字符串。
        /// </summary>
        internal static string en_BBI_RUNCONTINUE {
            get {
                return ResourceManager.GetString("en_BBI_RUNCONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunOnce 的本地化字符串。
        /// </summary>
        internal static string en_BBI_RUNONCE {
            get {
                return ResourceManager.GetString("en_BBI_RUNONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunStop 的本地化字符串。
        /// </summary>
        internal static string en_BBI_RUNSTOP {
            get {
                return ResourceManager.GetString("en_BBI_RUNSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        internal static string en_BBI_SYSTEMSET {
            get {
                return ResourceManager.GetString("en_BBI_SYSTEMSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VendorInfo 的本地化字符串。
        /// </summary>
        internal static string en_BBI_VENDORINFO {
            get {
                return ResourceManager.GetString("en_BBI_VENDORINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentRoutine 的本地化字符串。
        /// </summary>
        internal static string en_BEI_CURRRENTROUTINE {
            get {
                return ResourceManager.GetString("en_BEI_CURRRENTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string en_BSBI_ACCOUNT {
            get {
                return ResourceManager.GetString("en_BSBI_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardState: 的本地化字符串。
        /// </summary>
        internal static string en_BSBI_BOARDSTATE {
            get {
                return ResourceManager.GetString("en_BSBI_BOARDSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraState: 的本地化字符串。
        /// </summary>
        internal static string en_BSBI_CAMERASTATE {
            get {
                return ResourceManager.GetString("en_BSBI_CAMERASTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string en_BSBI_HELP {
            get {
                return ResourceManager.GetString("en_BSBI_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routine 的本地化字符串。
        /// </summary>
        internal static string en_BSBI_ROUTINE {
            get {
                return ResourceManager.GetString("en_BSBI_ROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SerialPort 的本地化字符串。
        /// </summary>
        internal static string en_BSBI_SERIALPORTSTATE {
            get {
                return ResourceManager.GetString("en_BSBI_SERIALPORTSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set 的本地化字符串。
        /// </summary>
        internal static string en_BSBI_SET {
            get {
                return ResourceManager.GetString("en_BSBI_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClientName: 的本地化字符串。
        /// </summary>
        internal static string en_BSTI_CLIENTNAME {
            get {
                return ResourceManager.GetString("en_BSTI_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account: 的本地化字符串。
        /// </summary>
        internal static string en_BSTI_CURRENTACCOUNT {
            get {
                return ResourceManager.GetString("en_BSTI_CURRENTACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentTime: 的本地化字符串。
        /// </summary>
        internal static string en_BSTI_CURRENTTIME {
            get {
                return ResourceManager.GetString("en_BSTI_CURRENTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnableAlgorithm 的本地化字符串。
        /// </summary>
        internal static string en_CHKE_ENABLEALGORITHM {
            get {
                return ResourceManager.GetString("en_CHKE_ENABLEALGORITHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnableLastRoutine 的本地化字符串。
        /// </summary>
        internal static string en_CHKE_ENABLELASTROUTINE {
            get {
                return ResourceManager.GetString("en_CHKE_ENABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveAll 的本地化字符串。
        /// </summary>
        internal static string en_CHKE_SAVEALL {
            get {
                return ResourceManager.GetString("en_CHKE_SAVEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveNG 的本地化字符串。
        /// </summary>
        internal static string en_CHKE_SAVENG {
            get {
                return ResourceManager.GetString("en_CHKE_SAVENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOK 的本地化字符串。
        /// </summary>
        internal static string en_CHKE_SAVEOK {
            get {
                return ResourceManager.GetString("en_CHKE_SAVEOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dialog For New Routine 的本地化字符串。
        /// </summary>
        internal static string en_FRM_NEWROUTINE {
            get {
                return ResourceManager.GetString("en_FRM_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dialog For Routine Manager 的本地化字符串。
        /// </summary>
        internal static string en_FRM_ROUTINEMANAGER {
            get {
                return ResourceManager.GetString("en_FRM_ROUTINEMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dialog For Setting Routine Parameter 的本地化字符串。
        /// </summary>
        internal static string en_FRM_SETROUTINEPARAMETER {
            get {
                return ResourceManager.GetString("en_FRM_SETROUTINEPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlgorithmParameter 的本地化字符串。
        /// </summary>
        internal static string en_GRPC_ALGORITHMPARAMETER {
            get {
                return ResourceManager.GetString("en_GRPC_ALGORITHMPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preprocess 的本地化字符串。
        /// </summary>
        internal static string en_GRPC_PREPROCESS {
            get {
                return ResourceManager.GetString("en_GRPC_PREPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProcessParameter 的本地化字符串。
        /// </summary>
        internal static string en_GRPC_PROCESSPARAMETER {
            get {
                return ResourceManager.GetString("en_GRPC_PROCESSPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppLanguage: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_APPLANGUAGE {
            get {
                return ResourceManager.GetString("en_LBLC_APPLANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraExposure 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_CAMERAEXPOSURE {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERAEXPOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraGain 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_CAMERAGAIN {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraNameForBarcode: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_CAMERANAMEFORBARCODE {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERANAMEFORBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClientName: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_CLIENTNAME {
            get {
                return ResourceManager.GetString("en_LBLC_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeType 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_CODETYPE {
            get {
                return ResourceManager.GetString("en_LBLC_CODETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pos: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_COORDINATE {
            get {
                return ResourceManager.GetString("en_LBLC_COORDINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DirectoryName: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_DIRECTORYNAME {
            get {
                return ResourceManager.GetString("en_LBLC_DIRECTORYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Promotion 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_DIRECTORYPROMPT {
            get {
                return ResourceManager.GetString("en_LBLC_DIRECTORYPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elapse: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_ELAPSETIME {
            get {
                return ResourceManager.GetString("en_LBLC_ELAPSETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OKColor 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_FOUNDCOLOR {
            get {
                return ResourceManager.GetString("en_LBLC_FOUNDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GrayValue: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_GRAYVALUE {
            get {
                return ResourceManager.GetString("en_LBLC_GRAYVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageName: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_IMAGENAME {
            get {
                return ResourceManager.GetString("en_LBLC_IMAGENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Judge Area 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_JUDGEAREA {
            get {
                return ResourceManager.GetString("en_LBLC_JUDGEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NGColor 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_NOTFOUNDCOLOR {
            get {
                return ResourceManager.GetString("en_LBLC_NOTFOUNDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PacketEnd: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_PACKETEND {
            get {
                return ResourceManager.GetString("en_LBLC_PACKETEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PacketHeader: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_PACKETHEADER {
            get {
                return ResourceManager.GetString("en_LBLC_PACKETHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Enter New Routine Name 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_PROMOTION {
            get {
                return ResourceManager.GetString("en_LBLC_PROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProNG: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_PRONG {
            get {
                return ResourceManager.GetString("en_LBLC_PRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProOK: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_PROOK {
            get {
                return ResourceManager.GetString("en_LBLC_PROOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProAll: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_PROTOTAL {
            get {
                return ResourceManager.GetString("en_LBLC_PROTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProYRT: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_PROYIELDRATIO {
            get {
                return ResourceManager.GetString("en_LBLC_PROYIELDRATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResultSeparator: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_RESULTSEPARATOR {
            get {
                return ResourceManager.GetString("en_LBLC_RESULTSEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RoutineDirectory: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_ROUTINEDIRECTORY {
            get {
                return ResourceManager.GetString("en_LBLC_ROUTINEDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SearchByName 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_SEARCHBYNAMES {
            get {
                return ResourceManager.GetString("en_LBLC_SEARCHBYNAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SerialPortNameForBarcode: 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_SERIALPORTNAMEFORBARCODE {
            get {
                return ResourceManager.GetString("en_LBLC_SERIALPORTNAMEFORBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeOut 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_TIMEOUT {
            get {
                return ResourceManager.GetString("en_LBLC_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FindNum 的本地化字符串。
        /// </summary>
        internal static string en_LBLC_TOBEFOUNDNUM {
            get {
                return ResourceManager.GetString("en_LBLC_TOBEFOUNDNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        internal static string en_RUN {
            get {
                return ResourceManager.GetString("en_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Parameter 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_APPLYPARAMETER {
            get {
                return ResourceManager.GetString("en_SBTN_APPLYPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculate Judge 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_CALCULATEJUDGE {
            get {
                return ResourceManager.GetString("en_SBTN_CALCULATEJUDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetCamera 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_CAMERASET {
            get {
                return ResourceManager.GetString("en_SBTN_CAMERASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("en_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_CLEARROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_CLEARROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("en_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_COUNTCLEAR {
            get {
                return ResourceManager.GetString("en_SBTN_COUNTCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_DELETEROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_DELETEROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_EDITROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_EDITROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_EXIT {
            get {
                return ResourceManager.GetString("en_SBTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TestContinue 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_GRABCONTINUE {
            get {
                return ResourceManager.GetString("en_SBTN_GRABCONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GrabStop 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_GRABSTOP {
            get {
                return ResourceManager.GetString("en_SBTN_GRABSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspect Area 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_INSPECTAREA {
            get {
                return ResourceManager.GetString("en_SBTN_INSPECTAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_LAST {
            get {
                return ResourceManager.GetString("en_SBTN_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadImage 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_LOADIMAGE {
            get {
                return ResourceManager.GetString("en_SBTN_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_LOADROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_NEWROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_NEXT {
            get {
                return ResourceManager.GetString("en_SBTN_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveParameter 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_SAVEPARAMETER {
            get {
                return ResourceManager.GetString("en_SBTN_SAVEPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_SEARCH {
            get {
                return ResourceManager.GetString("en_SBTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TestOffline 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_TESTOFFLINE {
            get {
                return ResourceManager.GetString("en_SBTN_TESTOFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TestOnce 的本地化字符串。
        /// </summary>
        internal static string en_SBTN_TESTONLINE {
            get {
                return ResourceManager.GetString("en_SBTN_TESTONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string en_SELECT {
            get {
                return ResourceManager.GetString("en_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string en_STOP {
            get {
                return ResourceManager.GetString("en_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Topbest Technology Limited 的本地化字符串。
        /// </summary>
        internal static string en_VENDORINFO {
            get {
                return ResourceManager.GetString("en_VENDORINFO", resourceCulture);
            }
        }
    }
}
