//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProVision.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProVision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行采集图像.
        /// </summary>
        internal static string chs_BTN_ACQUIREIMAGE {
            get {
                return ResourceManager.GetString("chs_BTN_ACQUIREIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加标定方案.
        /// </summary>
        internal static string chs_BTN_ADDCALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("chs_BTN_ADDCALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算标定结果.
        /// </summary>
        internal static string chs_BTN_CALCULATECALIBRATION {
            get {
                return ResourceManager.GetString("chs_BTN_CALCULATECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出标定.
        /// </summary>
        internal static string chs_BTN_EXITCALIBRATION {
            get {
                return ResourceManager.GetString("chs_BTN_EXITCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行匹配定位.
        /// </summary>
        internal static string chs_BTN_MATCHLOCATION {
            get {
                return ResourceManager.GetString("chs_BTN_MATCHLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置标定方案.
        /// </summary>
        internal static string chs_BTN_RESETCALIBRATION {
            get {
                return ResourceManager.GetString("chs_BTN_RESETCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存标定方案.
        /// </summary>
        internal static string chs_BTN_SAVECALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("chs_BTN_SAVECALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置匹配模型.
        /// </summary>
        internal static string chs_BTN_SETMATCHMODEL {
            get {
                return ResourceManager.GetString("chs_BTN_SETMATCHMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证标定结果.
        /// </summary>
        internal static string chs_BTN_VARIFYCALIBRATION {
            get {
                return ResourceManager.GetString("chs_BTN_VARIFYCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基于九点标定.
        /// </summary>
        internal static string chs_FRM_CALIBRATEPOINTBASED {
            get {
                return ResourceManager.GetString("chs_FRM_CALIBRATEPOINTBASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特征点类型.
        /// </summary>
        internal static string chs_GRPB_FEATUREPOINTTYPE {
            get {
                return ResourceManager.GetString("chs_GRPB_FEATUREPOINTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轴1移动步长.
        /// </summary>
        internal static string chs_LBL_AXIS1STEP {
            get {
                return ResourceManager.GetString("chs_LBL_AXIS1STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轴2移动步长.
        /// </summary>
        internal static string chs_LBL_AXIS2STEP {
            get {
                return ResourceManager.GetString("chs_LBL_AXIS2STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物理误差.
        /// </summary>
        internal static string chs_LBL_CALIBRATEPHYSICALERROR {
            get {
                return ResourceManager.GetString("chs_LBL_CALIBRATEPHYSICALERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 像素误差.
        /// </summary>
        internal static string chs_LBL_CALIBRATEPIXELERROR {
            get {
                return ResourceManager.GetString("chs_LBL_CALIBRATEPIXELERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标定结果.
        /// </summary>
        internal static string chs_LBL_CALIBRATERESULT {
            get {
                return ResourceManager.GetString("chs_LBL_CALIBRATERESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斜切角(Theta).
        /// </summary>
        internal static string chs_LBL_CHAMFERANGLE {
            get {
                return ResourceManager.GetString("chs_LBL_CHAMFERANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旋转角(Phi).
        /// </summary>
        internal static string chs_LBL_ROTATEANGLE {
            get {
                return ResourceManager.GetString("chs_LBL_ROTATEANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平缩放(Sx).
        /// </summary>
        internal static string chs_LBL_SCALEX {
            get {
                return ResourceManager.GetString("chs_LBL_SCALEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直缩放(Sy).
        /// </summary>
        internal static string chs_LBL_SCALEY {
            get {
                return ResourceManager.GetString("chs_LBL_SCALEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平偏移(Tx).
        /// </summary>
        internal static string chs_LBL_TRANSLATEX {
            get {
                return ResourceManager.GetString("chs_LBL_TRANSLATEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直偏移(Ty).
        /// </summary>
        internal static string chs_LBL_TRANSLATEY {
            get {
                return ResourceManager.GetString("chs_LBL_TRANSLATEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定式特征点.
        /// </summary>
        internal static string chs_RDBTN_FIXEDPOINT {
            get {
                return ResourceManager.GetString("chs_RDBTN_FIXEDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动式特征点.
        /// </summary>
        internal static string chs_RDBTN_MOBILEPOINT {
            get {
                return ResourceManager.GetString("chs_RDBTN_MOBILEPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcquireImage.
        /// </summary>
        internal static string en_BTN_ACQUIREIMAGE {
            get {
                return ResourceManager.GetString("en_BTN_ACQUIREIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCalbration.
        /// </summary>
        internal static string en_BTN_ADDCALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("en_BTN_ADDCALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateCalibration.
        /// </summary>
        internal static string en_BTN_CALCULATECALIBRATION {
            get {
                return ResourceManager.GetString("en_BTN_CALCULATECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitCalibration.
        /// </summary>
        internal static string en_BTN_EXITCALIBRATION {
            get {
                return ResourceManager.GetString("en_BTN_EXITCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocateByMacth.
        /// </summary>
        internal static string en_BTN_MATCHLOCATION {
            get {
                return ResourceManager.GetString("en_BTN_MATCHLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetCalibration.
        /// </summary>
        internal static string en_BTN_RESETCALIBRATION {
            get {
                return ResourceManager.GetString("en_BTN_RESETCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveCalibration.
        /// </summary>
        internal static string en_BTN_SAVECALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("en_BTN_SAVECALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMacthModel.
        /// </summary>
        internal static string en_BTN_SETMATCHMODEL {
            get {
                return ResourceManager.GetString("en_BTN_SETMATCHMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerifyCalibration.
        /// </summary>
        internal static string en_BTN_VARIFYCALIBRATION {
            get {
                return ResourceManager.GetString("en_BTN_VARIFYCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibrateBasedOnPoint.
        /// </summary>
        internal static string en_FRM_CALIBRATEPOINTBASED {
            get {
                return ResourceManager.GetString("en_FRM_CALIBRATEPOINTBASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeOfFeaturePoint.
        /// </summary>
        internal static string en_GRPB_FEATUREPOINTTYPE {
            get {
                return ResourceManager.GetString("en_GRPB_FEATUREPOINTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis1Step.
        /// </summary>
        internal static string en_LBL_AXIS1STEP {
            get {
                return ResourceManager.GetString("en_LBL_AXIS1STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis2Step.
        /// </summary>
        internal static string en_LBL_AXIS2STEP {
            get {
                return ResourceManager.GetString("en_LBL_AXIS2STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhysicalError.
        /// </summary>
        internal static string en_LBL_CALIBRATEPHYSICALERROR {
            get {
                return ResourceManager.GetString("en_LBL_CALIBRATEPHYSICALERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelError.
        /// </summary>
        internal static string en_LBL_CALIBRATEPIXELERROR {
            get {
                return ResourceManager.GetString("en_LBL_CALIBRATEPIXELERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibrateResult.
        /// </summary>
        internal static string en_LBL_CALIBRATERESULT {
            get {
                return ResourceManager.GetString("en_LBL_CALIBRATERESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle(Theta).
        /// </summary>
        internal static string en_LBL_CHAMFERANGLE {
            get {
                return ResourceManager.GetString("en_LBL_CHAMFERANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle(Phi).
        /// </summary>
        internal static string en_LBL_ROTATEANGLE {
            get {
                return ResourceManager.GetString("en_LBL_ROTATEANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleX.
        /// </summary>
        internal static string en_LBL_SCALEX {
            get {
                return ResourceManager.GetString("en_LBL_SCALEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleY.
        /// </summary>
        internal static string en_LBL_SCALEY {
            get {
                return ResourceManager.GetString("en_LBL_SCALEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslateX.
        /// </summary>
        internal static string en_LBL_TRANSLATEX {
            get {
                return ResourceManager.GetString("en_LBL_TRANSLATEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslateY.
        /// </summary>
        internal static string en_LBL_TRANSLATEY {
            get {
                return ResourceManager.GetString("en_LBL_TRANSLATEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedPoint.
        /// </summary>
        internal static string en_RDBTN_FIXEDPOINT {
            get {
                return ResourceManager.GetString("en_RDBTN_FIXEDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePoint.
        /// </summary>
        internal static string en_RDBTN_MOBILEPOINT {
            get {
                return ResourceManager.GetString("en_RDBTN_MOBILEPOINT", resourceCulture);
            }
        }
    }
}
