//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圆环.
        /// </summary>
        internal static string chs_BBI_ANNULUS {
            get {
                return ResourceManager.GetString("chs_BBI_ANNULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圆形.
        /// </summary>
        internal static string chs_BBI_CIRCLE {
            get {
                return ResourceManager.GetString("chs_BBI_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有向圆弧.
        /// </summary>
        internal static string chs_BBI_CIRCULARARC {
            get {
                return ResourceManager.GetString("chs_BBI_CIRCULARARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除活动ROI.
        /// </summary>
        internal static string chs_BBI_DELETEACTIVE {
            get {
                return ResourceManager.GetString("chs_BBI_DELETEACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除所有ROI.
        /// </summary>
        internal static string chs_BBI_DELETEALL {
            get {
                return ResourceManager.GetString("chs_BBI_DELETEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矢量线段.
        /// </summary>
        internal static string chs_BBI_LINE {
            get {
                return ResourceManager.GetString("chs_BBI_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载图像.
        /// </summary>
        internal static string chs_BBI_LOADIMAGE {
            get {
                return ResourceManager.GetString("chs_BBI_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 齐轴矩形.
        /// </summary>
        internal static string chs_BBI_RECTANGLE1 {
            get {
                return ResourceManager.GetString("chs_BBI_RECTANGLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仿射矩形.
        /// </summary>
        internal static string chs_BBI_RECTANGLE2 {
            get {
                return ResourceManager.GetString("chs_BBI_RECTANGLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置窗口.
        /// </summary>
        internal static string chs_BBI_RESETWINDOW {
            get {
                return ResourceManager.GetString("chs_BBI_RESETWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 局部放大.
        /// </summary>
        internal static string chs_BCHKI_MAGNIFY {
            get {
                return ResourceManager.GetString("chs_BCHKI_MAGNIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动图像.
        /// </summary>
        internal static string chs_BCHKI_MOVE {
            get {
                return ResourceManager.GetString("chs_BCHKI_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无操作.
        /// </summary>
        internal static string chs_BCHKI_NONE {
            get {
                return ResourceManager.GetString("chs_BCHKI_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放图像.
        /// </summary>
        internal static string chs_BCHKI_ZOOM {
            get {
                return ResourceManager.GetString("chs_BCHKI_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string chs_CHKE_ADD {
            get {
                return ResourceManager.GetString("chs_CHKE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string chs_CHKE_DELETE {
            get {
                return ResourceManager.GetString("chs_CHKE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连续.
        /// </summary>
        internal static string chs_CHKE_MODECONTINUE {
            get {
                return ResourceManager.GetString("chs_CHKE_MODECONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点动.
        /// </summary>
        internal static string chs_CHKE_MODEJOG {
            get {
                return ResourceManager.GetString("chs_CHKE_MODEJOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        internal static string chs_CHKE_MODIFY {
            get {
                return ResourceManager.GetString("chs_CHKE_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速.
        /// </summary>
        internal static string chs_CHKE_SPEEDHIGH {
            get {
                return ResourceManager.GetString("chs_CHKE_SPEEDHIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低速.
        /// </summary>
        internal static string chs_CHKE_SPEEDLOW {
            get {
                return ResourceManager.GetString("chs_CHKE_SPEEDLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中速.
        /// </summary>
        internal static string chs_CHKE_SPEEDMEDIUM {
            get {
                return ResourceManager.GetString("chs_CHKE_SPEEDMEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新波特率.
        /// </summary>
        internal static string chs_CHKE_UPDATEBAUDRATE {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATEBAUDRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新品牌.
        /// </summary>
        internal static string chs_CHKE_UPDATECAMERABRAND {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATECAMERABRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新曝光.
        /// </summary>
        internal static string chs_CHKE_UPDATECAMERAEXPOSURE {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATECAMERAEXPOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新帧率.
        /// </summary>
        internal static string chs_CHKE_UPDATECAMERAFPS {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATECAMERAFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新增益.
        /// </summary>
        internal static string chs_CHKE_UPDATECAMERAGAIN {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATECAMERAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新名称.
        /// </summary>
        internal static string chs_CHKE_UPDATECAMERANAME {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATECAMERANAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新序号.
        /// </summary>
        internal static string chs_CHKE_UPDATECAMERASN {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATECAMERASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新数据位.
        /// </summary>
        internal static string chs_CHKE_UPDATEDATABITS {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATEDATABITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新校验位.
        /// </summary>
        internal static string chs_CHKE_UPDATEPARITY {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATEPARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新端口项.
        /// </summary>
        internal static string chs_CHKE_UPDATESELECTION {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATESELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新停止位.
        /// </summary>
        internal static string chs_CHKE_UPDATESTOPBITS {
            get {
                return ResourceManager.GetString("chs_CHKE_UPDATESTOPBITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        internal static string chs_DISABLELASTROUTINE {
            get {
                return ResourceManager.GetString("chs_DISABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        internal static string chs_ENABLELASTROUTINE {
            get {
                return ResourceManager.GetString("chs_ENABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户登录.
        /// </summary>
        internal static string chs_FRM_LOGIN {
            get {
                return ResourceManager.GetString("chs_FRM_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域定义与修改.
        /// </summary>
        internal static string chs_FRM_MODIFYREGION {
            get {
                return ResourceManager.GetString("chs_FRM_MODIFYREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI 交互操作窗口.
        /// </summary>
        internal static string chs_FRM_ROIINTERACTIVE {
            get {
                return ResourceManager.GetString("chs_FRM_ROIINTERACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置配置.
        /// </summary>
        internal static string chs_FRM_SETCONFIG {
            get {
                return ResourceManager.GetString("chs_FRM_SETCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具坐标系偏移.
        /// </summary>
        internal static string chs_FRM_TOOLCENTEROFFSET {
            get {
                return ResourceManager.GetString("chs_FRM_TOOLCENTEROFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户详情.
        /// </summary>
        internal static string chs_GRPC_ACCOUNTDETAIL {
            get {
                return ResourceManager.GetString("chs_GRPC_ACCOUNTDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户与密码.
        /// </summary>
        internal static string chs_GRPC_ACCOUNTPROMOTION {
            get {
                return ResourceManager.GetString("chs_GRPC_ACCOUNTPROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户详情.
        /// </summary>
        internal static string chs_GRPC_ACCOUNTSDETAIL {
            get {
                return ResourceManager.GetString("chs_GRPC_ACCOUNTSDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 板卡配置.
        /// </summary>
        internal static string chs_GRPC_CFGBOARD {
            get {
                return ResourceManager.GetString("chs_GRPC_CFGBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机配置.
        /// </summary>
        internal static string chs_GRPC_CFGCAMERA {
            get {
                return ResourceManager.GetString("chs_GRPC_CFGCAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口配置.
        /// </summary>
        internal static string chs_GRPC_CFGSERIALPORT {
            get {
                return ResourceManager.GetString("chs_GRPC_CFGSERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket配置.
        /// </summary>
        internal static string chs_GRPC_CFGSOCKET {
            get {
                return ResourceManager.GetString("chs_GRPC_CFGSOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统配置.
        /// </summary>
        internal static string chs_GRPC_CFGSYSTEM {
            get {
                return ResourceManager.GetString("chs_GRPC_CFGSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web配置.
        /// </summary>
        internal static string chs_GRPC_CFGWEB {
            get {
                return ResourceManager.GetString("chs_GRPC_CFGWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模式/步距.
        /// </summary>
        internal static string chs_GRPC_MODESTEP {
            get {
                return ResourceManager.GetString("chs_GRPC_MODESTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作选项.
        /// </summary>
        internal static string chs_GRPC_OPERATIONOPTION {
            get {
                return ResourceManager.GetString("chs_GRPC_OPERATIONOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作提示.
        /// </summary>
        internal static string chs_GRPC_OPERATIONPROMOTION {
            get {
                return ResourceManager.GetString("chs_GRPC_OPERATIONPROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        internal static string chs_LBL_ACCOUNT {
            get {
                return ResourceManager.GetString("chs_LBL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限:.
        /// </summary>
        internal static string chs_LBL_ACCOUNTAUTHORITY {
            get {
                return ResourceManager.GetString("chs_LBL_ACCOUNTAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户列表.
        /// </summary>
        internal static string chs_LBL_ACCOUNTLIST {
            get {
                return ResourceManager.GetString("chs_LBL_ACCOUNTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称:.
        /// </summary>
        internal static string chs_LBL_ACCOUNTNAME {
            get {
                return ResourceManager.GetString("chs_LBL_ACCOUNTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码:.
        /// </summary>
        internal static string chs_LBL_ACCOUNTPASSWORD {
            get {
                return ResourceManager.GetString("chs_LBL_ACCOUNTPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误提示.
        /// </summary>
        internal static string chs_LBL_ERRORPROMOTION {
            get {
                return ResourceManager.GetString("chs_LBL_ERRORPROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string chs_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("chs_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定义区域列表.
        /// </summary>
        internal static string chs_LBLC_AREALIST {
            get {
                return ResourceManager.GetString("chs_LBLC_AREALIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波特率.
        /// </summary>
        internal static string chs_LBLC_BAUDRATE {
            get {
                return ResourceManager.GetString("chs_LBLC_BAUDRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机品牌.
        /// </summary>
        internal static string chs_LBLC_CAMERABRAND {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERABRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机曝光.
        /// </summary>
        internal static string chs_LBLC_CAMERAEXPOSURE {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERAEXPOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机帧率.
        /// </summary>
        internal static string chs_LBLC_CAMERAFPS {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERAFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机增益.
        /// </summary>
        internal static string chs_LBLC_CAMERAGAIN {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机名称.
        /// </summary>
        internal static string chs_LBLC_CAMERANAME {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERANAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识码相机名称.
        /// </summary>
        internal static string chs_LBLC_CAMERANAMEFOR2DBARCODE {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERANAMEFOR2DBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中相机的配置.
        /// </summary>
        internal static string chs_LBLC_CAMERAPROMPT {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERAPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机序号.
        /// </summary>
        internal static string chs_LBLC_CAMERASN {
            get {
                return ResourceManager.GetString("chs_LBLC_CAMERASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户名称.
        /// </summary>
        internal static string chs_LBLC_CLIENTNAME {
            get {
                return ResourceManager.GetString("chs_LBLC_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据位.
        /// </summary>
        internal static string chs_LBLC_DATABITS {
            get {
                return ResourceManager.GetString("chs_LBLC_DATABITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用上次程式.
        /// </summary>
        internal static string chs_LBLC_ENABLELASTROUTINE {
            get {
                return ResourceManager.GetString("chs_LBLC_ENABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点动步距(:mm).
        /// </summary>
        internal static string chs_LBLC_JOGSTEP {
            get {
                return ResourceManager.GetString("chs_LBLC_JOGSTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件语言.
        /// </summary>
        internal static string chs_LBLC_LANGUAGEVERSION {
            get {
                return ResourceManager.GetString("chs_LBLC_LANGUAGEVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作选项.
        /// </summary>
        internal static string chs_LBLC_OPERATION {
            get {
                return ResourceManager.GetString("chs_LBLC_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包尾字符.
        /// </summary>
        internal static string chs_LBLC_PACKENDSTR {
            get {
                return ResourceManager.GetString("chs_LBLC_PACKENDSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包头字符.
        /// </summary>
        internal static string chs_LBLC_PACKHEADSTR {
            get {
                return ResourceManager.GetString("chs_LBLC_PACKHEADSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验位.
        /// </summary>
        internal static string chs_LBLC_PARITY {
            get {
                return ResourceManager.GetString("chs_LBLC_PARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一点坐标R:.
        /// </summary>
        internal static string chs_LBLC_POINTR1 {
            get {
                return ResourceManager.GetString("chs_LBLC_POINTR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二点坐标R:.
        /// </summary>
        internal static string chs_LBLC_POINTR2 {
            get {
                return ResourceManager.GetString("chs_LBLC_POINTR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一点坐标X:.
        /// </summary>
        internal static string chs_LBLC_POINTX1 {
            get {
                return ResourceManager.GetString("chs_LBLC_POINTX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二点坐标X:.
        /// </summary>
        internal static string chs_LBLC_POINTX2 {
            get {
                return ResourceManager.GetString("chs_LBLC_POINTX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一点坐标Y:.
        /// </summary>
        internal static string chs_LBLC_POINTY1 {
            get {
                return ResourceManager.GetString("chs_LBLC_POINTY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二点坐标Y:.
        /// </summary>
        internal static string chs_LBLC_POINTY2 {
            get {
                return ResourceManager.GetString("chs_LBLC_POINTY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示:.
        /// </summary>
        internal static string chs_LBLC_PROMPT {
            get {
                return ResourceManager.GetString("chs_LBLC_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注:.
        /// </summary>
        internal static string chs_LBLC_REAMARK {
            get {
                return ResourceManager.GetString("chs_LBLC_REAMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果分隔符.
        /// </summary>
        internal static string chs_LBLC_RESULTSPLITSTR {
            get {
                return ResourceManager.GetString("chs_LBLC_RESULTSPLITSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式目录.
        /// </summary>
        internal static string chs_LBLC_ROUTINEDIRECTORY {
            get {
                return ResourceManager.GetString("chs_LBLC_ROUTINEDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识码串口名称.
        /// </summary>
        internal static string chs_LBLC_SERIALPORTNAMEFOR2DBARCODE {
            get {
                return ResourceManager.GetString("chs_LBLC_SERIALPORTNAMEFOR2DBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中串口的配置.
        /// </summary>
        internal static string chs_LBLC_SERIALPORTPROMPT {
            get {
                return ResourceManager.GetString("chs_LBLC_SERIALPORTPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口选项.
        /// </summary>
        internal static string chs_LBLC_SERIALPORTSELECTION {
            get {
                return ResourceManager.GetString("chs_LBLC_SERIALPORTSELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止位.
        /// </summary>
        internal static string chs_LBLC_STOPBITS {
            get {
                return ResourceManager.GetString("chs_LBLC_STOPBITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏移坐标X.
        /// </summary>
        internal static string chs_LBLC_TOOLCENTEROFFSETX {
            get {
                return ResourceManager.GetString("chs_LBLC_TOOLCENTEROFFSETX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏移坐标Y.
        /// </summary>
        internal static string chs_LBLC_TOOLCENTEROFFSETY {
            get {
                return ResourceManager.GetString("chs_LBLC_TOOLCENTEROFFSETY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算偏移.
        /// </summary>
        internal static string chs_LKLBL_CALCULATETOOLCENTEROFFSET {
            get {
                return ResourceManager.GetString("chs_LKLBL_CALCULATETOOLCENTEROFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取坐标.
        /// </summary>
        internal static string chs_LKLBL_GETPOSITION1 {
            get {
                return ResourceManager.GetString("chs_LKLBL_GETPOSITION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取坐标.
        /// </summary>
        internal static string chs_LKLBL_GETPOSITION2 {
            get {
                return ResourceManager.GetString("chs_LKLBL_GETPOSITION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定位坐标.
        /// </summary>
        internal static string chs_LKLBL_GOTOPOSITION1 {
            get {
                return ResourceManager.GetString("chs_LKLBL_GOTOPOSITION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定位坐标.
        /// </summary>
        internal static string chs_LKLBL_GOTOPOSITION2 {
            get {
                return ResourceManager.GetString("chs_LKLBL_GOTOPOSITION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注区域.
        /// </summary>
        internal static string chs_RBP_ROIINTERACTIVE {
            get {
                return ResourceManager.GetString("chs_RBP_ROIINTERACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像功能组.
        /// </summary>
        internal static string chs_RBPGRP_IMAGEFUNCTION {
            get {
                return ResourceManager.GetString("chs_RBPGRP_IMAGEFUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交互操作组.
        /// </summary>
        internal static string chs_RBPGRP_OPERATION {
            get {
                return ResourceManager.GetString("chs_RBPGRP_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域形状组.
        /// </summary>
        internal static string chs_RBPGRP_ROISHAPE {
            get {
                return ResourceManager.GetString("chs_RBPGRP_ROISHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视图选项组.
        /// </summary>
        internal static string chs_RBPGRP_VIEWOPTION {
            get {
                return ResourceManager.GetString("chs_RBPGRP_VIEWOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string chs_RBTN_ADD {
            get {
                return ResourceManager.GetString("chs_RBTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string chs_RBTN_DELETE {
            get {
                return ResourceManager.GetString("chs_RBTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        internal static string chs_RBTN_MODIFY {
            get {
                return ResourceManager.GetString("chs_RBTN_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string chs_SBTN_ADDAXES {
            get {
                return ResourceManager.GetString("chs_SBTN_ADDAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string chs_SBTN_ADDINPUT {
            get {
                return ResourceManager.GetString("chs_SBTN_ADDINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string chs_SBTN_ADDOUTPUT {
            get {
                return ResourceManager.GetString("chs_SBTN_ADDOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机标定.
        /// </summary>
        internal static string chs_SBTN_CAMERACALIBRATE {
            get {
                return ResourceManager.GetString("chs_SBTN_CAMERACALIBRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认更新.
        /// </summary>
        internal static string chs_SBTN_CAMERACONFIRMUPDATE {
            get {
                return ResourceManager.GetString("chs_SBTN_CAMERACONFIRMUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string chs_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("chs_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string chs_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("chs_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string chs_SBTN_CONFIRMA {
            get {
                return ResourceManager.GetString("chs_SBTN_CONFIRMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string chs_SBTN_CONFIRMG {
            get {
                return ResourceManager.GetString("chs_SBTN_CONFIRMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定义区域.
        /// </summary>
        internal static string chs_SBTN_DEFINEREGION {
            get {
                return ResourceManager.GetString("chs_SBTN_DEFINEREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string chs_SBTN_DELETEAXES {
            get {
                return ResourceManager.GetString("chs_SBTN_DELETEAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string chs_SBTN_DELETEINPUT {
            get {
                return ResourceManager.GetString("chs_SBTN_DELETEINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string chs_SBTN_DELETEOUTPUT {
            get {
                return ResourceManager.GetString("chs_SBTN_DELETEOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载参数.
        /// </summary>
        internal static string chs_SBTN_DOWNLOADPARAMETER {
            get {
                return ResourceManager.GetString("chs_SBTN_DOWNLOADPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 枚举串口.
        /// </summary>
        internal static string chs_SBTN_ENUMERATESERIALPORT {
            get {
                return ResourceManager.GetString("chs_SBTN_ENUMERATESERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 擦除区域.
        /// </summary>
        internal static string chs_SBTN_ERASEREGION {
            get {
                return ResourceManager.GetString("chs_SBTN_ERASEREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string chs_SBTN_EXIT {
            get {
                return ResourceManager.GetString("chs_SBTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载图像.
        /// </summary>
        internal static string chs_SBTN_LOAD {
            get {
                return ResourceManager.GetString("chs_SBTN_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string chs_SBTN_LOGIN {
            get {
                return ResourceManager.GetString("chs_SBTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认更新.
        /// </summary>
        internal static string chs_SBTN_SERIALPORTCONFIRMUPDATE {
            get {
                return ResourceManager.GetString("chs_SBTN_SERIALPORTCONFIRMUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string chs_SBTN_UPDATEAXES {
            get {
                return ResourceManager.GetString("chs_SBTN_UPDATEAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string chs_SBTN_UPDATEINPUT {
            get {
                return ResourceManager.GetString("chs_SBTN_UPDATEINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string chs_SBTN_UPDATEOUTPUT {
            get {
                return ResourceManager.GetString("chs_SBTN_UPDATEOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上载参数.
        /// </summary>
        internal static string chs_SBTN_UPLOADPARAMETER {
            get {
                return ResourceManager.GetString("chs_SBTN_UPLOADPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匹配模型.
        /// </summary>
        internal static string chs_TLSTRP_MATCHMODEL {
            get {
                return ResourceManager.GetString("chs_TLSTRP_MATCHMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旋转中心.
        /// </summary>
        internal static string chs_TLSTRPBTN_ROTATECENTER {
            get {
                return ResourceManager.GetString("chs_TLSTRPBTN_ROTATECENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机设置.
        /// </summary>
        internal static string chs_TLSTRPBTN_SETCAMERA {
            get {
                return ResourceManager.GetString("chs_TLSTRPBTN_SETCAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 九点标定.
        /// </summary>
        internal static string chs_TLSTRPMITM_CALIBRATE9POINT {
            get {
                return ResourceManager.GetString("chs_TLSTRPMITM_CALIBRATE9POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标定板标定.
        /// </summary>
        internal static string chs_TLSTRPMITM_CALIBRATPLATE {
            get {
                return ResourceManager.GetString("chs_TLSTRPMITM_CALIBRATPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连续采集.
        /// </summary>
        internal static string chs_TSTRPBTN_ACQUIRECONTINUE {
            get {
                return ResourceManager.GetString("chs_TSTRPBTN_ACQUIRECONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单张采集(软).
        /// </summary>
        internal static string chs_TSTRPBTN_ACQUIREONCE {
            get {
                return ResourceManager.GetString("chs_TSTRPBTN_ACQUIREONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户管理.
        /// </summary>
        internal static string chs_XTAB_ACCOUNTMANAGER {
            get {
                return ResourceManager.GetString("chs_XTAB_ACCOUNTMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员权限.
        /// </summary>
        internal static string chs_XTAB_ADMINISTRATORAUTHORITY {
            get {
                return ResourceManager.GetString("chs_XTAB_ADMINISTRATORAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般权限.
        /// </summary>
        internal static string chs_XTABP_GENERALAUTHORITY {
            get {
                return ResourceManager.GetString("chs_XTABP_GENERALAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轴配置.
        /// </summary>
        internal static string chs_XTBP_CFGAXES {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 板卡配置.
        /// </summary>
        internal static string chs_XTBP_CFGBOARD {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机配置.
        /// </summary>
        internal static string chs_XTBP_CFGCAMERA {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGCAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入配置.
        /// </summary>
        internal static string chs_XTBP_CFGINPUT {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出配置.
        /// </summary>
        internal static string chs_XTBP_CFGOUTPUT {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口配置.
        /// </summary>
        internal static string chs_XTBP_CFGSERIALPORT {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGSERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket配置.
        /// </summary>
        internal static string chs_XTBP_CFGSOCKET {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGSOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统配置.
        /// </summary>
        internal static string chs_XTBP_CFGSYSTEM {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web配置.
        /// </summary>
        internal static string chs_XTBP_CFGWEB {
            get {
                return ResourceManager.GetString("chs_XTBP_CFGWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulus.
        /// </summary>
        internal static string en_BBI_ANNULUS {
            get {
                return ResourceManager.GetString("en_BBI_ANNULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string en_BBI_CIRCLE {
            get {
                return ResourceManager.GetString("en_BBI_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CircularArc.
        /// </summary>
        internal static string en_BBI_CIRCULARARC {
            get {
                return ResourceManager.GetString("en_BBI_CIRCULARARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ActiveROI.
        /// </summary>
        internal static string en_BBI_DELETEACTIVE {
            get {
                return ResourceManager.GetString("en_BBI_DELETEACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete AllROI.
        /// </summary>
        internal static string en_BBI_DELETEALL {
            get {
                return ResourceManager.GetString("en_BBI_DELETEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string en_BBI_LINE {
            get {
                return ResourceManager.GetString("en_BBI_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        internal static string en_BBI_LOADIMAGE {
            get {
                return ResourceManager.GetString("en_BBI_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle1.
        /// </summary>
        internal static string en_BBI_RECTANGLE1 {
            get {
                return ResourceManager.GetString("en_BBI_RECTANGLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle2.
        /// </summary>
        internal static string en_BBI_RECTANGLE2 {
            get {
                return ResourceManager.GetString("en_BBI_RECTANGLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Window.
        /// </summary>
        internal static string en_BBI_RESETWINDOW {
            get {
                return ResourceManager.GetString("en_BBI_RESETWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Magnify.
        /// </summary>
        internal static string en_BCHKI_MAGNIFY {
            get {
                return ResourceManager.GetString("en_BCHKI_MAGNIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Image.
        /// </summary>
        internal static string en_BCHKI_MOVE {
            get {
                return ResourceManager.GetString("en_BCHKI_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string en_BCHKI_NONE {
            get {
                return ResourceManager.GetString("en_BCHKI_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Image.
        /// </summary>
        internal static string en_BCHKI_ZOOM {
            get {
                return ResourceManager.GetString("en_BCHKI_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string en_CHKE_ADD {
            get {
                return ResourceManager.GetString("en_CHKE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string en_CHKE_DELETE {
            get {
                return ResourceManager.GetString("en_CHKE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string en_CHKE_MODECONTINUE {
            get {
                return ResourceManager.GetString("en_CHKE_MODECONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog.
        /// </summary>
        internal static string en_CHKE_MODEJOG {
            get {
                return ResourceManager.GetString("en_CHKE_MODEJOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string en_CHKE_MODIFY {
            get {
                return ResourceManager.GetString("en_CHKE_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string en_CHKE_SPEEDHIGH {
            get {
                return ResourceManager.GetString("en_CHKE_SPEEDHIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string en_CHKE_SPEEDLOW {
            get {
                return ResourceManager.GetString("en_CHKE_SPEEDLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string en_CHKE_SPEEDMEDIUM {
            get {
                return ResourceManager.GetString("en_CHKE_SPEEDMEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateBaudRate.
        /// </summary>
        internal static string en_CHKE_UPDATEBAUDRATE {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATEBAUDRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateBrand.
        /// </summary>
        internal static string en_CHKE_UPDATECAMERABRAND {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATECAMERABRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateExposure.
        /// </summary>
        internal static string en_CHKE_UPDATECAMERAEXPOSURE {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATECAMERAEXPOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateFPS.
        /// </summary>
        internal static string en_CHKE_UPDATECAMERAFPS {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATECAMERAFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateGain.
        /// </summary>
        internal static string en_CHKE_UPDATECAMERAGAIN {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATECAMERAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateName.
        /// </summary>
        internal static string en_CHKE_UPDATECAMERANAME {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATECAMERANAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateSN.
        /// </summary>
        internal static string en_CHKE_UPDATECAMERASN {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATECAMERASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDataBits.
        /// </summary>
        internal static string en_CHKE_UPDATEDATABITS {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATEDATABITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateParity.
        /// </summary>
        internal static string en_CHKE_UPDATEPARITY {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATEPARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatePort.
        /// </summary>
        internal static string en_CHKE_UPDATESELECTION {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATESELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateStopBits.
        /// </summary>
        internal static string en_CHKE_UPDATESTOPBITS {
            get {
                return ResourceManager.GetString("en_CHKE_UPDATESTOPBITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string en_DISABLELASTROUTINE {
            get {
                return ResourceManager.GetString("en_DISABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string en_ENABLELASTROUTINE {
            get {
                return ResourceManager.GetString("en_ENABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string en_FRM_LOGIN {
            get {
                return ResourceManager.GetString("en_FRM_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefineAndModifyArea.
        /// </summary>
        internal static string en_FRM_MODIFYREGION {
            get {
                return ResourceManager.GetString("en_FRM_MODIFYREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI Interactive Frame.
        /// </summary>
        internal static string en_FRM_ROIINTERACTIVE {
            get {
                return ResourceManager.GetString("en_FRM_ROIINTERACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetConfig.
        /// </summary>
        internal static string en_FRM_SETCONFIG {
            get {
                return ResourceManager.GetString("en_FRM_SETCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolCenterOffset.
        /// </summary>
        internal static string en_FRM_TOOLCENTEROFFSET {
            get {
                return ResourceManager.GetString("en_FRM_TOOLCENTEROFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountDetail.
        /// </summary>
        internal static string en_GRPC_ACCOUNTDETAIL {
            get {
                return ResourceManager.GetString("en_GRPC_ACCOUNTDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountPassWord.
        /// </summary>
        internal static string en_GRPC_ACCOUNTPROMOTION {
            get {
                return ResourceManager.GetString("en_GRPC_ACCOUNTPROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountsDetail.
        /// </summary>
        internal static string en_GRPC_ACCOUNTSDETAIL {
            get {
                return ResourceManager.GetString("en_GRPC_ACCOUNTSDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardConfig.
        /// </summary>
        internal static string en_GRPC_CFGBOARD {
            get {
                return ResourceManager.GetString("en_GRPC_CFGBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraConfig.
        /// </summary>
        internal static string en_GRPC_CFGCAMERA {
            get {
                return ResourceManager.GetString("en_GRPC_CFGCAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialPortConfig.
        /// </summary>
        internal static string en_GRPC_CFGSERIALPORT {
            get {
                return ResourceManager.GetString("en_GRPC_CFGSERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocketConfig.
        /// </summary>
        internal static string en_GRPC_CFGSOCKET {
            get {
                return ResourceManager.GetString("en_GRPC_CFGSOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemConfig.
        /// </summary>
        internal static string en_GRPC_CFGSYSTEM {
            get {
                return ResourceManager.GetString("en_GRPC_CFGSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebConfig.
        /// </summary>
        internal static string en_GRPC_CFGWEB {
            get {
                return ResourceManager.GetString("en_GRPC_CFGWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode/Step.
        /// </summary>
        internal static string en_GRPC_MODESTEP {
            get {
                return ResourceManager.GetString("en_GRPC_MODESTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationOption.
        /// </summary>
        internal static string en_GRPC_OPERATIONOPTION {
            get {
                return ResourceManager.GetString("en_GRPC_OPERATIONOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationPromotion.
        /// </summary>
        internal static string en_GRPC_OPERATIONPROMOTION {
            get {
                return ResourceManager.GetString("en_GRPC_OPERATIONPROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string en_LBL_ACCOUNT {
            get {
                return ResourceManager.GetString("en_LBL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority:.
        /// </summary>
        internal static string en_LBL_ACCOUNTAUTHORITY {
            get {
                return ResourceManager.GetString("en_LBL_ACCOUNTAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountList.
        /// </summary>
        internal static string en_LBL_ACCOUNTLIST {
            get {
                return ResourceManager.GetString("en_LBL_ACCOUNTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string en_LBL_ACCOUNTNAME {
            get {
                return ResourceManager.GetString("en_LBL_ACCOUNTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWord:.
        /// </summary>
        internal static string en_LBL_ACCOUNTPASSWORD {
            get {
                return ResourceManager.GetString("en_LBL_ACCOUNTPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorPromotion.
        /// </summary>
        internal static string en_LBL_ERRORPROMOTION {
            get {
                return ResourceManager.GetString("en_LBL_ERRORPROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWord.
        /// </summary>
        internal static string en_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("en_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefineAreaList.
        /// </summary>
        internal static string en_LBLC_AREALIST {
            get {
                return ResourceManager.GetString("en_LBLC_AREALIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaudRate.
        /// </summary>
        internal static string en_LBLC_BAUDRATE {
            get {
                return ResourceManager.GetString("en_LBLC_BAUDRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraBrand.
        /// </summary>
        internal static string en_LBLC_CAMERABRAND {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERABRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposureTime.
        /// </summary>
        internal static string en_LBLC_CAMERAEXPOSURE {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERAEXPOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraFPS.
        /// </summary>
        internal static string en_LBLC_CAMERAFPS {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERAFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraGain.
        /// </summary>
        internal static string en_LBLC_CAMERAGAIN {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraName.
        /// </summary>
        internal static string en_LBLC_CAMERANAME {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERANAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraNameForBarcode.
        /// </summary>
        internal static string en_LBLC_CAMERANAMEFOR2DBARCODE {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERANAMEFOR2DBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraConfigForSelected.
        /// </summary>
        internal static string en_LBLC_CAMERAPROMPT {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERAPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNumber.
        /// </summary>
        internal static string en_LBLC_CAMERASN {
            get {
                return ResourceManager.GetString("en_LBLC_CAMERASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientName.
        /// </summary>
        internal static string en_LBLC_CLIENTNAME {
            get {
                return ResourceManager.GetString("en_LBLC_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBits.
        /// </summary>
        internal static string en_LBLC_DATABITS {
            get {
                return ResourceManager.GetString("en_LBLC_DATABITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableLastRoutine.
        /// </summary>
        internal static string en_LBLC_ENABLELASTROUTINE {
            get {
                return ResourceManager.GetString("en_LBLC_ENABLELASTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JogStep(:mm).
        /// </summary>
        internal static string en_LBLC_JOGSTEP {
            get {
                return ResourceManager.GetString("en_LBLC_JOGSTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppLanguage.
        /// </summary>
        internal static string en_LBLC_LANGUAGEVERSION {
            get {
                return ResourceManager.GetString("en_LBLC_LANGUAGEVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string en_LBLC_OPERATION {
            get {
                return ResourceManager.GetString("en_LBLC_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketEnd.
        /// </summary>
        internal static string en_LBLC_PACKENDSTR {
            get {
                return ResourceManager.GetString("en_LBLC_PACKENDSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketHeader.
        /// </summary>
        internal static string en_LBLC_PACKHEADSTR {
            get {
                return ResourceManager.GetString("en_LBLC_PACKHEADSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        internal static string en_LBLC_PARITY {
            get {
                return ResourceManager.GetString("en_LBLC_PARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point1_R.
        /// </summary>
        internal static string en_LBLC_POINTR1 {
            get {
                return ResourceManager.GetString("en_LBLC_POINTR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point2_R.
        /// </summary>
        internal static string en_LBLC_POINTR2 {
            get {
                return ResourceManager.GetString("en_LBLC_POINTR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point1_X:.
        /// </summary>
        internal static string en_LBLC_POINTX1 {
            get {
                return ResourceManager.GetString("en_LBLC_POINTX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point2_X:.
        /// </summary>
        internal static string en_LBLC_POINTX2 {
            get {
                return ResourceManager.GetString("en_LBLC_POINTX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point1_Y:.
        /// </summary>
        internal static string en_LBLC_POINTY1 {
            get {
                return ResourceManager.GetString("en_LBLC_POINTY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point2_Y:.
        /// </summary>
        internal static string en_LBLC_POINTY2 {
            get {
                return ResourceManager.GetString("en_LBLC_POINTY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        internal static string en_LBLC_PROMPT {
            get {
                return ResourceManager.GetString("en_LBLC_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark:.
        /// </summary>
        internal static string en_LBLC_REAMARK {
            get {
                return ResourceManager.GetString("en_LBLC_REAMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        internal static string en_LBLC_RESULTSPLITSTR {
            get {
                return ResourceManager.GetString("en_LBLC_RESULTSPLITSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoutineDir.
        /// </summary>
        internal static string en_LBLC_ROUTINEDIRECTORY {
            get {
                return ResourceManager.GetString("en_LBLC_ROUTINEDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialPortNameForBarcode.
        /// </summary>
        internal static string en_LBLC_SERIALPORTNAMEFOR2DBARCODE {
            get {
                return ResourceManager.GetString("en_LBLC_SERIALPORTNAMEFOR2DBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortConfigForSelected.
        /// </summary>
        internal static string en_LBLC_SERIALPORTPROMPT {
            get {
                return ResourceManager.GetString("en_LBLC_SERIALPORTPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortSelection.
        /// </summary>
        internal static string en_LBLC_SERIALPORTSELECTION {
            get {
                return ResourceManager.GetString("en_LBLC_SERIALPORTSELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopBits.
        /// </summary>
        internal static string en_LBLC_STOPBITS {
            get {
                return ResourceManager.GetString("en_LBLC_STOPBITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolCenterOffsetX.
        /// </summary>
        internal static string en_LBLC_TOOLCENTEROFFSETX {
            get {
                return ResourceManager.GetString("en_LBLC_TOOLCENTEROFFSETX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolCenterOffsetY.
        /// </summary>
        internal static string en_LBLC_TOOLCENTEROFFSETY {
            get {
                return ResourceManager.GetString("en_LBLC_TOOLCENTEROFFSETY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateOffset.
        /// </summary>
        internal static string en_LKLBL_CALCULATETOOLCENTEROFFSET {
            get {
                return ResourceManager.GetString("en_LKLBL_CALCULATETOOLCENTEROFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPosition.
        /// </summary>
        internal static string en_LKLBL_GETPOSITION1 {
            get {
                return ResourceManager.GetString("en_LKLBL_GETPOSITION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPosition.
        /// </summary>
        internal static string en_LKLBL_GETPOSITION2 {
            get {
                return ResourceManager.GetString("en_LKLBL_GETPOSITION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoToPosition.
        /// </summary>
        internal static string en_LKLBL_GOTOPOSITION1 {
            get {
                return ResourceManager.GetString("en_LKLBL_GOTOPOSITION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoToPosition.
        /// </summary>
        internal static string en_LKLBL_GOTOPOSITION2 {
            get {
                return ResourceManager.GetString("en_LKLBL_GOTOPOSITION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region of interest.
        /// </summary>
        internal static string en_RBP_ROIINTERACTIVE {
            get {
                return ResourceManager.GetString("en_RBP_ROIINTERACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image function.
        /// </summary>
        internal static string en_RBPGRP_IMAGEFUNCTION {
            get {
                return ResourceManager.GetString("en_RBPGRP_IMAGEFUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive operation.
        /// </summary>
        internal static string en_RBPGRP_OPERATION {
            get {
                return ResourceManager.GetString("en_RBPGRP_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region shape.
        /// </summary>
        internal static string en_RBPGRP_ROISHAPE {
            get {
                return ResourceManager.GetString("en_RBPGRP_ROISHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View option.
        /// </summary>
        internal static string en_RBPGRP_VIEWOPTION {
            get {
                return ResourceManager.GetString("en_RBPGRP_VIEWOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string en_RBTN_ADD {
            get {
                return ResourceManager.GetString("en_RBTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string en_RBTN_DELETE {
            get {
                return ResourceManager.GetString("en_RBTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string en_RBTN_MODIFY {
            get {
                return ResourceManager.GetString("en_RBTN_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string en_SBTN_ADDAXES {
            get {
                return ResourceManager.GetString("en_SBTN_ADDAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string en_SBTN_ADDINPUT {
            get {
                return ResourceManager.GetString("en_SBTN_ADDINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string en_SBTN_ADDOUTPUT {
            get {
                return ResourceManager.GetString("en_SBTN_ADDOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraCalibrate.
        /// </summary>
        internal static string en_SBTN_CAMERACALIBRATE {
            get {
                return ResourceManager.GetString("en_SBTN_CAMERACALIBRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigmUpdate.
        /// </summary>
        internal static string en_SBTN_CAMERACONFIRMUPDATE {
            get {
                return ResourceManager.GetString("en_SBTN_CAMERACONFIRMUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string en_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("en_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string en_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("en_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string en_SBTN_CONFIRMA {
            get {
                return ResourceManager.GetString("en_SBTN_CONFIRMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string en_SBTN_CONFIRMG {
            get {
                return ResourceManager.GetString("en_SBTN_CONFIRMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefineArea.
        /// </summary>
        internal static string en_SBTN_DEFINEREGION {
            get {
                return ResourceManager.GetString("en_SBTN_DEFINEREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string en_SBTN_DELETEAXES {
            get {
                return ResourceManager.GetString("en_SBTN_DELETEAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string en_SBTN_DELETEINPUT {
            get {
                return ResourceManager.GetString("en_SBTN_DELETEINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string en_SBTN_DELETEOUTPUT {
            get {
                return ResourceManager.GetString("en_SBTN_DELETEOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownLoadPara.
        /// </summary>
        internal static string en_SBTN_DOWNLOADPARAMETER {
            get {
                return ResourceManager.GetString("en_SBTN_DOWNLOADPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumeratePorts.
        /// </summary>
        internal static string en_SBTN_ENUMERATESERIALPORT {
            get {
                return ResourceManager.GetString("en_SBTN_ENUMERATESERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EraseArea.
        /// </summary>
        internal static string en_SBTN_ERASEREGION {
            get {
                return ResourceManager.GetString("en_SBTN_ERASEREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string en_SBTN_EXIT {
            get {
                return ResourceManager.GetString("en_SBTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadImage.
        /// </summary>
        internal static string en_SBTN_LOAD {
            get {
                return ResourceManager.GetString("en_SBTN_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string en_SBTN_LOGIN {
            get {
                return ResourceManager.GetString("en_SBTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmUpdate.
        /// </summary>
        internal static string en_SBTN_SERIALPORTCONFIRMUPDATE {
            get {
                return ResourceManager.GetString("en_SBTN_SERIALPORTCONFIRMUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string en_SBTN_UPDATEAXES {
            get {
                return ResourceManager.GetString("en_SBTN_UPDATEAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string en_SBTN_UPDATEINPUT {
            get {
                return ResourceManager.GetString("en_SBTN_UPDATEINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string en_SBTN_UPDATEOUTPUT {
            get {
                return ResourceManager.GetString("en_SBTN_UPDATEOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpLoadPara.
        /// </summary>
        internal static string en_SBTN_UPLOADPARAMETER {
            get {
                return ResourceManager.GetString("en_SBTN_UPLOADPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchModel.
        /// </summary>
        internal static string en_TLSTRP_MATCHMODEL {
            get {
                return ResourceManager.GetString("en_TLSTRP_MATCHMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RotateCenter.
        /// </summary>
        internal static string en_TLSTRPBTN_ROTATECENTER {
            get {
                return ResourceManager.GetString("en_TLSTRPBTN_ROTATECENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetCamera.
        /// </summary>
        internal static string en_TLSTRPBTN_SETCAMERA {
            get {
                return ResourceManager.GetString("en_TLSTRPBTN_SETCAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate9PointBased.
        /// </summary>
        internal static string en_TLSTRPMITM_CALIBRATE9POINT {
            get {
                return ResourceManager.GetString("en_TLSTRPMITM_CALIBRATE9POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibratePlateBased.
        /// </summary>
        internal static string en_TLSTRPMITM_CALIBRATPLATE {
            get {
                return ResourceManager.GetString("en_TLSTRPMITM_CALIBRATPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcquireContinuous.
        /// </summary>
        internal static string en_TSTRPBTN_ACQUIRECONTINUE {
            get {
                return ResourceManager.GetString("en_TSTRPBTN_ACQUIRECONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcquireOnce(I).
        /// </summary>
        internal static string en_TSTRPBTN_ACQUIREONCE {
            get {
                return ResourceManager.GetString("en_TSTRPBTN_ACQUIREONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountManager.
        /// </summary>
        internal static string en_XTABP_ACCOUNTMANAGER {
            get {
                return ResourceManager.GetString("en_XTABP_ACCOUNTMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdministratorAuthority.
        /// </summary>
        internal static string en_XTABP_ADMINISTRATORAUTHORITY {
            get {
                return ResourceManager.GetString("en_XTABP_ADMINISTRATORAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralAuthority.
        /// </summary>
        internal static string en_XTABP_GENERALAUTHORITY {
            get {
                return ResourceManager.GetString("en_XTABP_GENERALAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxesConfig.
        /// </summary>
        internal static string en_XTBP_CFGAXES {
            get {
                return ResourceManager.GetString("en_XTBP_CFGAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardConfig.
        /// </summary>
        internal static string en_XTBP_CFGBOARD {
            get {
                return ResourceManager.GetString("en_XTBP_CFGBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraConfig.
        /// </summary>
        internal static string en_XTBP_CFGCAMERA {
            get {
                return ResourceManager.GetString("en_XTBP_CFGCAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputConfig.
        /// </summary>
        internal static string en_XTBP_CFGINPUT {
            get {
                return ResourceManager.GetString("en_XTBP_CFGINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutConfig.
        /// </summary>
        internal static string en_XTBP_CFGOUTPUT {
            get {
                return ResourceManager.GetString("en_XTBP_CFGOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialPortConfig.
        /// </summary>
        internal static string en_XTBP_CFGSERIALPORT {
            get {
                return ResourceManager.GetString("en_XTBP_CFGSERIALPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocketConfig.
        /// </summary>
        internal static string en_XTBP_CFGSOCKET {
            get {
                return ResourceManager.GetString("en_XTBP_CFGSOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemConfig.
        /// </summary>
        internal static string en_XTBP_CFGSYSTEM {
            get {
                return ResourceManager.GetString("en_XTBP_CFGSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebConfig.
        /// </summary>
        internal static string en_XTBP_CFGWEB {
            get {
                return ResourceManager.GetString("en_XTBP_CFGWEB", resourceCulture);
            }
        }
    }
}
